<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Hudson Technologies</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="manifest" href="site.webmanifest"> -->
        <link rel="shortcut icon" type="image/x-icon" href="<?= base_url()?>assets/img/favicon.ico">
    
        <!-- CSS here -->
        <link rel="stylesheet" href="<?= base_url()?>assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/owl.carousel.min.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/slicknav.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/flaticon.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/progressbar_barfiller.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/gijgo.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/animate.min.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/animated-headline.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/magnific-popup.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/fontawesome-all.min.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/themify-icons.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/slick.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/nice-select.css">
        <link rel="stylesheet" href="<?= base_url()?>assets/css/style.css">
        
    </head>
    <body class="full-wrapper">
        <!-- ? Preloader Start -->
        
        <!-- Preloader Start-->
       
        
            <?=$layouts['header']?>
    
        <main>
        <!-- breadcrumb Start-->
        <div class="page-notification" style="padding-bottom: 30px;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">about</a></li> 
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb End-->
        <!-- About Area Start -->
        <div class="about-area">
            <div class="container">
                <div class="row justify-content-start">
                    <div class="col-lg-10">
                        <div class="section-tittle mb-60 text-start pt-10">
                            <h2 style="font-size:60px">Terms of Use</h2>
 <p> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Hudson Export Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
<br><br>
<p>
<h1 style="font-size:30px;"><b >Membership Eligibility</h1>
<p style="color:black">Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent or legal guardian.
As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Hudson Export reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Hudson Export  notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.
</p>
<br>
    <p>
<h1 style="font-size:30px;"><b >Your Account and Registration Obligations</h1>
<p style="color:black">If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.
Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.
You agree that Hudson Export shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.
If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences there from.
</p>
<br>
    <p>
<h1 style="font-size:30px;"><b >Communications </h1>
<p style="color:black">When You use the Platform or send emails or other data,
 information or communication to us, You agree and understand that You are communicating with Us through 
 electronic records and You consent to receive communications via electronic records from Us periodically and as and when required.
 We may communicate with you by email or by such other mode of communication, electronic or otherwise.</p>
    <br>
    <p>
<h1 style="font-size:30px;"><b >
Use of the Platform
</h1>
<p style="color:black">You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:
1.	You shall not host, display, upload, modify, publish, transmit, update or share any information which:<br>
(a) belongs to another person and to which You does not have any right to;<br>
(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic,
 paedophilic, libellous, invasive of another's privacy, hateful, or racially, 
 ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, 
 or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing
 including but not limited to "indecent representation of women" within the meaning of the Indecent Representation 
 of Women (Prohibition) Act, 1986;<br>
(c) is misleading in any way;<br>
(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;<br>
(e) harasses or advocates harassment of another person;<br>
(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";<br>
(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;<br>
(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];<br>
(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;<br>
(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);<br>
(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;<br>
(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;<br>
(m) contains video, photographs, or images of another person (with a minor or an adult).
(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;<br>
(o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Hudson Export prior written consent means a communication coming from Hudson Export Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;<br>
(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;<br>
(q) interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services;<br>
(r) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.<br>
(s) harm minors in any way;<br>
(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;<br>
(u) violates any law for the time being in force;<br>
(v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;<br>
(w) impersonate another person;<br>
(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancel bots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;<br>
(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.<br>
(z) shall not be false, inaccurate or misleading;<br>
</p>
    
    
    
                        </div>
                    </div>
                    
        <!-- About Area End -->
        <!--? Popular Items Start -->
		      <!-- Popular Items End -->
        <!--? Services Area Start -->
       
        <!--? Services Area End -->
    </main>

    <?=$layouts['footer']?>
    <!-- Footer End-->
  <!--? Search model Begin -->
  <div class="search-model-box">
      <div class="h-100 d-flex align-items-center justify-content-center">
          <div class="search-close-btn">+</div>
          <form class="search-model-form">
              <input type="text" id="search-input" placeholder="Searching key.....">
          </form>
      </div>
  </div>
  <!-- Search model end -->
  <!-- Scroll Up -->
  <div id="back-top" >
      <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
  </div>
  
  <!-- JS here -->
  <!-- Jquery, Popper, Bootstrap -->
  <script src="<?= base_url()?>assets/js/vendor/modernizr-3.5.0.min.js"></script>
  <script src="<?= base_url()?>assets/js/vendor/jquery-1.12.4.min.js"></script>
  <script src="<?= base_url()?>assets/js/popper.min.js"></script>
  <script src="<?= base_url()?>assets/js/bootstrap.min.js"></script>
  
  <!-- Slick-slider , Owl-Carousel ,slick-nav -->
  <script src="<?= base_url()?>assets/js/owl.carousel.min.js"></script>
  <script src="<?= base_url()?>assets/js/slick.min.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.slicknav.min.js"></script>
  
  <!-- One Page, Animated-HeadLin, Date Picker -->
  <script src="<?= base_url()?>assets/js/wow.min.js"></script>
  <script src="<?= base_url()?>assets/js/animated.headline.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.magnific-popup.js"></script>
  <script src="<?= base_url()?>assets/js/gijgo.min.js"></script>
  
  <!-- Nice-select, sticky,Progress -->
  <script src="<?= base_url()?>assets/js/jquery.nice-select.min.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.sticky.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.barfiller.js"></script>
  
  <!-- counter , waypoint,Hover Direction -->
  <script src="<?= base_url()?>assets/js/jquery.counterup.min.js"></script>
  <script src="<?= base_url()?>assets/js/waypoints.min.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.countdown.min.js"></script>
  <script src="<?= base_url()?>assets/js/hover-direction-snake.min.js"></script>
  
  <!-- contact js -->
  <script src="<?= base_url()?>assets/js/contact.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.form.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.validate.min.js"></script>
  <script src="<?= base_url()?>assets/js/mail-script.js"></script>
  <script src="<?= base_url()?>assets/js/jquery.ajaxchimp.min.js"></script>
  
  <!-- Jquery Plugins, main Jquery -->	
  <script src="<?= base_url()?>assets/js/plugins.js"></script>
  <script src="<?= base_url()?>assets/js/main.js"></script>
  
</body>
</html>